name: Publish to PyPI and update files

# GitHub events that triggers the workflow:
on:
  release:
    types:
      - published

jobs:
  call_tests_workflow:
    name: Test
    uses: ./.github/workflows/test.yaml

  publish:
    name: Publish to PyPI
    needs: [call_tests_workflow]
    runs-on: ubuntu-latest
    environment: release

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Hatch
        uses: pypa/hatch@install

      - name: Check if the release tag matches the version
        uses: samuelcolvin/check-python-version@v4.1
        with:
          version_file_path: rendercv_tinytex/__init__.py

      - name: Build
        run: |
          hatch build

      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
